### ISSUE TITLE
Can not save document.

### ISSUE THREAD

**Issue by alober2** [vert-x3/vertx-mongo-client#10]
I try it, but can not save document.
import io.vertx.groovy.ext.mongo.MongoClient;
def options = [
	config:[
		"host": "127.0.0.1",
		"port": 27017,
		"pool_size": 15,
		"db_name": "test_bug"
	]
]

def client = MongoClient.createShared(vertx, options.config);
def document = [
	_id: 1234,
	title: "Language"
]
client.insert("bug_test", document, { res ->
	if (res.succeeded()) {
		def id = res.result()
		println("Inserted book with id ${id}")
	} else {
		res.cause().printStackTrace()
	}
});

**Comment by purplefox** [comment]
Can you provide a reproducer please?

**Comment by alober2** [comment]
Hi, I write a java file to do that. it show java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.CharSequence
// vertx run Server.java

import io.vertx.ext.mongo.MongoClient;
import java.util.*;
import io.vertx.core.json.*;
import io.vertx.core.AbstractVerticle;

public class Server extends AbstractVerticle {
    public void start() {
        JsonObject config = new JsonObject();
        config.put("host", "127.0.0.1");
        config.put("port", 27017);
        config.put("db_name", "bug_test");
        MongoClient client = MongoClient.createShared(vertx, config);
        JsonObject document = new JsonObject().put("title", "The Hobbit");
        // here it happened
        document.put("_id", 123456);

        client.insert("bug_test", document, res -> {
            if (res.succeeded()) {
                String id = res.result();
                System.out.println("Inserted with id " + id);
            } else {
                res.cause().printStackTrace();
            }
        });
    }
}

**Comment by purplefox** [comment]
Thanks. This should be fixed now in master.
