### ISSUE TITLE
useObjectId produces inconsistent results with find() and findOne()

### ISSUE THREAD

**Issue by jgeth** [vert-x3/vertx-mongo-client#104]
Changed behavior since 3.4.0

When returning results via `find()` pre-3.4 the `ObjectId` is encoded in the list of JsonObjects. As of 3.4 this is decoded (see line 254: `results.forEach(this::decodeKeyWhenUseObjectId);`)

`JsonObject` returned via `findOne()` has consistently returned `ObjectId` encoded.

This could be on purpose or oversight, but I for one would prefer consistent default behavior whether returning a `List<JsonObject>` or single `JsonObject` containing an `ObjectId`.

**Comment by karianna** [comment]
Hmmm, will need to see where this change was introduced/

**Comment by jgeth** [comment]
https://github.com/vert-x3/vertx-mongo-client/commit/ee0edff7771de78de830f275bfc40a63d1d14efe

**Comment by karianna** [comment]
@jgeth I agree it should be consistent, so I think that we should change `findOne()` so that it also decodes
@johnoliver FYI - We accepted that PR deliberately but didn't list it as a breaking change (my bad).

**Comment by diabolicallabs** [comment]
I'm working on this as it's impacting my other project. Changing findOne to decode.

**Comment by diabolicallabs** [comment]
Just submitted PR for this

**Comment by johnoliver** [comment]
Think this was fixed by #107

**Comment by karianna** [comment]
@jgeth I'm closing this for now - please reopen if 3.5.0 doesn't work for you!
