### ISSUE TITLE
Update mongodb driver to 3.6.0

### ISSUE THREAD

**Issue by tanw** [vert-x3/vertx-mongo-client#108]
I am using the vertx 3.4.1 which also depends on mongodb driver 3.4.1. I ran into an issue that was reported in https://jira.mongodb.org/browse/JAVA-2421
I need to update my app's pom to use the mongo driver 3.4.2. Can the next Vertx release be updated to use mongo driver 3.4.2?

**Comment by aaloise** [comment]
Since version 3.6 of mongo driver is somehow about to be released, isn't it better to wait for it?

**Comment by aaloise** [comment]
MongoDB Java Async Driver v3.6 released

http://mongodb.github.io/mongo-java-driver/3.6/driver-async/getting-started/installation/

**Comment by vietj** [comment]
@karianna is that an upgrade we can have for 3.5.1 ?

**Comment by karianna** [comment]
Hmmm, maybe - 3.5.0 is fine, even 3.6.0-rc0 is fine, 3.6.0-rc1 breaks codec detection.  Still debugging.

**Comment by karianna** [comment]
@johnoliver knows all the codecs.

**Comment by karianna** [comment]
closed via #130
