### ISSUE TITLE
Cannot use aggregation framework

### ISSUE THREAD

**Issue by meshuga** [vert-x3/vertx-mongo-client#11]
Currently it's not possible to use aggregation framework with service. According to the documentation (http://docs.mongodb.org/manual/reference/command/aggregate/#dbcmd.aggregate) the structure of the command is as follows:
```
{
  aggregate: "<collection>",
  pipeline: [ <stage>, <...> ],
  explain: <boolean>,
  allowDiskUse: <boolean>,
  cursor: <document>
}
```
The thing is that the first parameter of JSON object is `aggregate` keyword and MongoDB (3.0.2 tested) mandates this structure. Unfortunately, the aggregation request passed to the client is as follows:
```
{
  pipeline: [ <stage>, <...> ],
... other commands
  aggregate: "<collection>",
}
```
Because of that MongoDB returns error: 
```
io.vertx.core.eventbus.ReplyException: Command failed with error 59: 'no such command: pipeline' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "no such command: pipeline", "code" : 59, "bad cmd" : { "pipeline" : [], "aggregate" : "collection_name" } }
```
It doesn't matter in which order I put fields to the proxy. I don't know the internals of the core vert.x, but from my research there is a problem with vertx-core which messes with the order of fields.

**Comment by purplefox** [comment]
Hmm, JSON does not provide any ordering guarantees. I don't think this is Vert.x specific, it's just the way JSON works.
I can't see anything here http://docs.mongodb.org/manual/reference/command/aggregate/#dbcmd.aggregate that says the fields have to be in a specific order.

**Comment by meshuga** [comment]
According to this document http://docs.mongodb.org/manual/tutorial/use-database-commands/ the first field has to be a command.

**Comment by purplefox** [comment]
Right... but JSON itself has no concept of "first key", in JSON keys are in no specific order.

Mongo uses BSON - which does have ordering and we convert our JSON to BSON, so I'm not sure how we would handle this.

Do you have any suggestion?

**Comment by purplefox** [comment]
I think we'd need to have adapt the runCommand method on the client to take the command name as first param

**Comment by purplefox** [comment]
One thing I am slightly puzzled about is although JSON itself provides no ordering, our own JsonObject implementation does.

Can you provide a simple reproducer that demonstrates the issue?

**Comment by meshuga** [comment]
Yes, adding the first parameter would be great. I can handle that ;)
I think tomorrow I'll send a reproducer and start a discussion on google groups about my team's concerns about this module :)

**Comment by purplefox** [comment]
BTW, please take a look at my latest post about mongo on the dev group :)

**Comment by meshuga** [comment]
https://gist.github.com/meshuga/b5a0ac1e797c082c6b3c

**Comment by purplefox** [comment]
This should be fixed now.
