### ISSUE TITLE
findOne NPE

### ISSUE THREAD

**Issue by ambye85** [vert-x3/vertx-mongo-client#111]
`mongoClient.findOne("books", query, null, res -> {...});` results in NPE. The [docs](https://github.com/vert-x3/vertx-mongo-client/blob/master/vertx-mongo-client/src/main/asciidoc/java/index.adoc#finding-documents) say `findOne` is just like `find`, yet `find()` doesn't have a `fields` parameter. The docs also say in relation to `FindOptions`:
> fields
>     The fields to return in the results. Defaults to null, meaning all fields will be returned

Granted, the `fields` parameter is not a `FindOptions` type.

If this is the expected behaviour of `findOne()`, could you clarify that in the docs?

**Comment by karianna** [comment]
@AshleyByeUK Can you give a more concrete code example where the NPE is thrown?

**Comment by karianna** [comment]
closing as no response
