### ISSUE TITLE
MongoClient stores IDs as string

### ISSUE THREAD

**Issue by DieterDePaepe** [vert-x3/vertx-mongo-client#114]
Mongoclient stores the `_id` field as a string rather than an `ObjectId` when `useObjectId == false` (default value).

This behavior was introduced in the [pull request](https://github.com/vert-x3/vertx-mongo-client/pull/38/commits/086323866d0acec50e90d84ee94aa5f15a82fd84) for issue #36. See `JsonObjectCodec#generateIdIfAbsentFromDocument`.

The main issue caused by this is that not all commands (can) ensure this behavior, eg: `updateWithOptions`, when used as an upsert, will create an `ObjectId` - see #97 - resulting in multiple id representations in the DB.
An additional disadvantage is that using string values for `_id` requires more storage space per document than an `ObjectId`.

**Comment by karianna** [comment]
@DieterDePaepe We've taken a look and agree that #97 is a bug and have put a help wanted label on that.  Hopefully a community contributor fixes it in the holiday break.  Please open more issues if you find that useObjectId is not being honoured elsewhere.
