### ISSUE TITLE
ReadConcernLevel is ignored completely

### ISSUE THREAD

**Issue by slnowak** [vert-x3/vertx-mongo-client#115]
According to MongoDB docs and ConnectionString class from `org.mongodb:mongodb-driver-core` (https://github.com/mongodb/mongo-java-driver/blob/master/driver-core/src/main/com/mongodb/ConnectionString.java) one should be able to set `readconcernlevel` property with possible values: `local/majority/linearizable`.

However, it seems like vertx-mongo-client completely ignores this settings. 
We're using the following code to create mongo driver instance:
`
 return MongoClient.createShared(vertx, new JsonObject().put("connection_string", configuration.connectionString()));
`

Under the hood, vertx-mongo-client uses `MongoClientOptionsParser` (https://github.com/vert-x3/vertx-mongo-client/blob/master/vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java) that completely ignores ReadConcern value.

Thus, resulting `com.mongodb.async.client.MongoClient` instance (MongoClientImpl) has nullable ReadConcern set.

**Comment by karianna** [comment]
#136 is the PR for this.
