### ISSUE TITLE
Vert.x create connection to bucket and Gridfs in mongo

### ISSUE THREAD

**Issue by nitinlodhe** [vert-x3/vertx-mongo-client#116]
Hi Team,
I have an app created in Vert.x where in I need to connect to a bucket to do CRUD operations and at the same time I need to connect to GridFs as well to store bulk docs.
I want to understand how can I open connection to bucket and GridFs both while starting my verticle.

I see this method to create GridFs connection:  GridFSBuckets.create(MongoDatabase database) [com.mongodb.async.client.MongoDatabase  ]

but at the same time I do not see a way to get the [com.mongodb.async.client.MongoDatabase ] from [io.vertx.ext.mongo.MongoClient]

Please assist.

**Comment by karianna** [comment]
see https://github.com/vert-x3/vertx-mongo-client/pull/105 and https://github.com/vert-x3/vertx-mongo-client/issues/83
