### ISSUE TITLE
MongoDB Async Driver version 3.5 new features ready support POJOs

### ISSUE THREAD

**Issue by leotu** [vert-x3/vertx-mongo-client#118]
What is the best practice to bring those two classes integrated into MongoClient
```java
org.bson.codecs.configuration.CodecRegistries.fromProviders
org.bson.codecs.configuration.CodecRegistries.fromRegistries
```

inside Vertx code ?
```java
io.vertx.ext.mongo.impl.MongoClientImpl.java
io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.java
```

Ref Docs.
http://mongodb.github.io/mongo-java-driver/3.5/whats-new/
http://mongodb.github.io/mongo-java-driver/3.5/driver-async/getting-started/quick-start-pojo/
http://rosslawley.co.uk/mongodb-pojo-support/

**Comment by karianna** [comment]
We'd need to upgrade to the 3.5.0 driver.  There's a request to go to 3.6.0, but a change between rc0 and rc1 there has broken... something. see  #108

**Comment by karianna** [comment]
@johnoliver found this:

`https://github.com/vert-x3/vertx-mongo-client/blob/master/vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java#L41`

Where we set the codec registry.  Is this what you're looking for?

**Comment by karianna** [comment]
FYI - Driver is updated to 3.6.0

**Comment by karianna** [comment]
@cleciusjm 3.5.0+
