### ISSUE TITLE
Nested Objects and Arrays materialized in their Java form

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-mongo-client#12]
The language bindings are intended to present JSON documents in their "native" form to each language. In the Groovy binding (and perhaps others) this is working for the root object, but not for any nested objects and/or arrays.  These are instead presented as JsonObject and/or JsonArray instances.

See the following thread for more info https://groups.google.com/forum/#!topic/vertx-dev/StuQ8pv3kWQ.

This gist demonstrates the issue -- https://gist.github.com/sfitts/73d4a2e2229466f5ccd3

**Comment by vietj** [comment]
Hi, this is solved with the change in master to use consistent Map/List in JsonObject / JsonArray in Vert.x core. See https://github.com/eclipse/vert.x/commit/085eb0d62318111b4e499d16e54fb96422411b3d

**Comment by sfitts** [comment]
This appears to have been reverted by https://github.com/eclipse/vert.x/commit/ef73b29cee5e5422f0c8ba0ca5eaf03e257f738b.  I can't re-open this issue so I'm going to create a new one - #13
