### ISSUE TITLE
What does bulkWrite() do when some writes fail?

### ISSUE THREAD

**Issue by leolux** [vert-x3/vertx-mongo-client#125]
Let's assume we want to replace 10 documents using bulkWrite(). What to expect from the API when one of these documents cannot be replaced because the document-id cannot be found in the collection? Will the remaining documents be written anyway?

**Comment by karianna** [comment]
@leolux Have you tried this with the native Mongo Driver?

**Comment by leolux** [comment]
no, but the behaviour should be identically to the underlying driver.
