### ISSUE TITLE
rxInsert without .subscribe is not inserting the document

### ISSUE THREAD

**Issue by bmenninga** [vert-x3/vertx-mongo-client#129]
I'm on 3.5 and trying to insert a document. 

This does not add the document
`mongoClient.rxInsert("documents", document).doOnError(e -> ..... );`

This does add the document
`mongoClient.rxInsert("documents", document).doOnError(e -> ..... ).subscribe(results -> ..... );`

Is this a bug, or am I missing something?

I'll use the deprecated .insertObservable for now.

**Comment by tsegismont** [comment]
This is not a bug. See http://vertx.io/docs/vertx-rx/java/#_async_result_support

> Such single are cold singles, and the corresponding API method is called on subscribe.

**Comment by bmenninga** [comment]
Okay, thank you! That's new to me. So I've added .subscribe(); to get it working again.
