### ISSUE TITLE
Nested Objects and Arrays materialized in their Java form

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-mongo-client#13]
This is a re-opening of #12 since the changes that were targetted to fix it were reverted.

The language bindings are intended to present JSON documents in their "native" form to each language. In the Groovy binding (and perhaps others) this is working for the root object, but not for any nested objects and/or arrays. These are instead presented as JsonObject and/or JsonArray instances.

See the following thread for more info https://groups.google.com/forum/#!topic/vertx-dev/StuQ8pv3kWQ.

This gist demonstrates the issue -- https://gist.github.com/sfitts/73d4a2e2229466f5ccd3

**Comment by sfitts** [comment]
Moved to https://github.com/vert-x3/vertx-lang-groovy/issues/5

**Comment by purplefox** [comment]
I'm going to look at this now

**Comment by purplefox** [comment]
Is this now fixed?

**Comment by sfitts** [comment]
Not until https://github.com/vert-x3/vertx-mongo-client/pull/22 is merged.
