### ISSUE TITLE
Mapping a MongoDB document's _id with Vert.x

### ISSUE THREAD

**Issue by underscorenico** [vert-x3/vertx-mongo-client#135]
I'm using Vert.x MongoDB client as well as Vert.x CodeGen (https://github.com/vert-x3/vertx-codegen). 

This is an example of my document:

    @DataObject
    public class Instrument {
    
      public static final String DB_TABLE = "instruments";
    
      private String id;
      private String instrumentId;
      private String name;
    }

<br> Since the model of my document (or entity) is annotated with `@DataObject`, how can tell Vert.x which field I want to use as Mongo's `_id`?

When using Spring (Data), one can annotate an entity with `@Document` and the field to be used as Mongo's `_id` with the annotation `@Id`. Is this possible in Vert.x?

If not, is there any turnaround?

Thanks!

**Comment by johnoliver** [comment]
You can use the constructor that takes a JsonObject and the toJson methods on the data object to define a custom mapping between json and your own fields.

**Comment by eriknyk** [comment]
@underscorenico you can do: 
```
@DataObject
public class Instrument {

public static final String DB_TABLE = "instruments";
  @JsonProperty("_id")
  private String id;
  private String instrumentId;
  private String name;
}
```
and 
```
Instrument i = Json.decodeValue(it.toString(), Instrument.class)
```
