### ISSUE TITLE
Determine and annotate mongo method that might return null so RxJava2 generates correct code

### ISSUE THREAD

**Issue by gaol** [vert-x3/vertx-mongo-client#142]
RxJava 2 does not allow to emit `null`.

However, methods like:
* `Single<JsonObject> io.vertx.reactivex.ext.mongo.MongoClient.rxFindOne()`
* `Single<JsonObject> io.vertx.reactivex.ext.mongo.MongoClient.rxFindOneAndUpdate()`
* some other methods too
emit null if they don't find any document.

The return type as `Maybe<JsonObject>` should be more appropriate so that `MaybeObserver.onComplete()` method can be called in case of no document found.

Related issues:
* https://github.com/vert-x3/vertx-rx/issues/133
* https://github.com/vert-x3/vertx-service-discovery/issues/86

**Comment by vietj** [comment]
I've made this issue more general purpose

**Comment by vietj** [comment]
@karianna is it an issue you can take care off ? it's not long but requires to know well the current API

**Comment by karianna** [comment]
I'll take a look and John can make sure I don't do anything insane :-)

**Comment by vietj** [comment]
thanks much appreciated

**Comment by cazacugmihai** [comment]
Is there any progress on this?

**Comment by karianna** [comment]
Unfortunately not - this is quite far down our priority list at the moment

**Comment by tsegismont** [comment]
@karianna @cazacugmihai I've submitted #194 

This issue has been filed some time ago and meanwhile quite a few methods have been fixed already (see for example https://github.com/vert-x3/vertx-mongo-client/pull/166).

I believe we could change the milestone to 3.8.0 (cc @vietj ). In this case I'll update the breaking changes page.

**Comment by karianna** [comment]
Is the 'master;  branch 3.8.0 or 4.0.0?

**Comment by tsegismont** [comment]
@karianna `master` is 4.0. If we change the target milestone I'll cherry-pick to the 3.8 branch.

**Comment by karianna** [comment]
Cool, It's not an issue for us personally but if you want it for 3.8.0 then I'm happy to move the milestone!

**Comment by tsegismont** [comment]
@karianna yes please, move it to `3.8.0`. Any chance that you could review the PR this week?

**Comment by karianna** [comment]
Added new milestone

**Comment by karianna** [comment]
@tsegismont Can you also submit a backport PR to the correct branch (I think it's 3.7.x)?

**Comment by karianna** [comment]
3.8 is fine in that case :-)
