### ISSUE TITLE
id field issue in 3.6 (fixed in PR #145)

### ISSUE THREAD

**Issue by doctorpangloss** [vert-x3/vertx-mongo-client#146]
Three tests currently fail after `vertx-mongo-client` started to get tested against 3.6. These are real exceptions due to a change in how the `id` field is dealt with in upserts, and it is fixed in https://github.com/vert-x3/vertx-mongo-client/pull/145 .

**Comment by vietj** [comment]
oh great

**Comment by vietj** [comment]
can you reference the fixes for 3.5.2 and mongo there https://github.com/vert-x3/issues/issues/352 ?

**Comment by karianna** [comment]
Will do if this makes it on time - I'll check with @johnoliver tomorrow

**Comment by karianna** [comment]
Fixed some time ago
