### ISSUE TITLE
Aggregate support in mongodb 3.6

### ISSUE THREAD

**Issue by bckfnn** [vert-x3/vertx-mongo-client#148]
mongodb 3.6 removes the possibility to call aggregate command without specifying a cursor. 

https://docs.mongodb.com/manual/release-notes/3.4-compatibility/index.html#deprecated-operations

so the old and well proven trick from 

https://vertx.io/docs/vertx-mongo-client/java/#_running_other_mongodb_commands

no longer works. The returned "result" array no longer exists, but instead a cursor document with a firstBatch array is returned. Sending the GET_MORE command to retrieve the next batch seems not to be possible.

It seems to me that using aggregation with mongo 3.6 require active support from the Vertx.x MongoDB Client, f.ex. with an aggregate(..) method that returns a ReadStream<JsonObject> similar to findBatch

**Comment by domenicoierullo** [comment]
Is there a trick to get around the problem?
I need help!

**Comment by domenicoierullo** [comment]
No ideas! Sorry,

**Comment by HendrikLanghammer** [comment]
This is how I worked around the problem for now:

1.) add the cursor to your command using a batch size larger than your maximum number of results:

`JsonObject command = new JsonObject().put("aggregate", COLLECTION).put("cursor", new JsonObject().put("batchSize", 1000)).put("pipeline", pipeline);`

2.) find your results in the new location:

`JsonArray jsonArray = res.result().getJsonObject("cursor").getJsonArray("firstBatch");`

Hope this saves anyone a couple of minutes.

**Comment by payuprashantg** [comment]
What is the status of this enhancement?

**Comment by karianna** [comment]
I think this is resolved and will land in 3.6.1

**Comment by limadelrey** [comment]
Is it on Vert.x's roadmap a reactive implementation of aggregate method (e.g. rxAggregate)?
