### ISSUE TITLE
mongodb driver 3.8.0

### ISSUE THREAD

**Issue by cazacugmihai** [vert-x3/vertx-mongo-client#151]
MongoDB driver `3.8.0` has added support for transactions. Can the library be updated to support this version?

Thank you for your efforts in maintaining this!

**Comment by vietj** [comment]
@limadelrey we don't know yet, if there is a contribution, definitely yes

**Comment by karianna** [comment]
Reactive Streams 4.0.2 drive is now in place.

**Comment by bjaanes** [comment]
But this does not add transaction support yet, I guess? @karianna

**Comment by karianna** [comment]
> But this does not add transaction support yet, I guess? @karianna

They are supported natively by the driver, but we do not have any specific API endpoints for this in the client

**Comment by bjaanes** [comment]
True, but to use them you have to create a client session and start the transactions and then commit or abort it. So I suppose we still need that. Is there a separate ticket for transaction support?

**Comment by karianna** [comment]
#158
