### ISSUE TITLE
Concatenating rx-Queries with .ConcatWith() produces IllegalStateException: more produced than requested

### ISSUE THREAD

**Issue by u3r** [vert-x3/vertx-mongo-client#153]
I encountered a bug when concatenating RX-ified Mongo queries:
**Expected behaviour:** 
The result of two queries is concatenated without error (even if one or both are Observable.empty().
 
**Actual behaviour:**
`java.lang.IllegalStateException: more produced than requested` is thrown and the rx-chain runs until vertx times out.

There is a workaround I found by accident (also shown in PR#152): Adding a `.doOnException(..log..)` to 
the concatenated query will 'fix' this problem even though it is never called.
Why that is I don't know.

PR #152  ([Linkt to code](https://github.com/vert-x3/vertx-mongo-client/pull/152/commits/34dbf64b1719fbaa0b5b9f4b41e3adf58c1fd1e6)) demonstrates the problem on Version 3.5.1.
One unittest will crash with an exception but continue running
The other (with an .doOnException(..log..)) will behave as expected even though the onException is never hit.

I tried the same code using the https://github.com/mongodb/mongo-java-driver-rx - which works as expected.

**Comment by tsegismont** [comment]
Closed in 69c31bf
