### ISSUE TITLE
How to obtain generated IDs after rxBulkWrite

### ISSUE THREAD

**Issue by cazacugmihai** [vert-x3/vertx-mongo-client#154]
Hi,

Is there a way to obtain the generated ids after using `rxBulkWrite` method?
I thought that the information will be stored in `MongoClientBulkWriteResult#upserts` but that field is empty, every time:

```
insertedCount = 100
matchedCount = 0
deletedCount = 0
modifiedCount = 0
upserts = {ArrayList@11734}  size = 0
```

Thanks!

**Comment by tsegismont** [comment]
This is possible now with #285
