### ISSUE TITLE
Groovy code not included in sources jar.

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-mongo-client#17]
It looks like it is supposed to be, but isn't.  I took a look and tried to figure out why this might be, but I don't know enough about the build ordering to really know for sure what is going on.

Not sure if it is related, but I see some errors relating to building the groovydocs.

**Comment by purplefox** [comment]
I'm guessing a codegen/docgen issue? @vietj what do you think?

**Comment by vietj** [comment]
it's more a packaging issue in vertx-ext-parent I think and should be addressed here

**Comment by purplefox** [comment]
@vietj can you close this if it's handled elsewhere?
