### ISSUE TITLE
vertx-mongo-client uses an old version of mongodb-driver-core

### ISSUE THREAD

**Issue by lukehutch** [vert-x3/vertx-mongo-client#177]
The `mongodb-driver-core` embedded into `vertx-mongo-client` needs to be updated. `vertx-mongo-client` uses an old version of `mongodb-driver-core`, which means it is not possible to also use `mongo-java-driver` in the same project as `vertx-mongo-client`, due to an ABI clash.

**Comment by karianna** [comment]
@lukehutch CAn you give us the details on the version numbers?

**Comment by lukehutch** [comment]
Sorry, in both vertx version 3.6.3 and 4.0.0-SNAPSHOT, `vertx-mongo-client` pulls in `mongodb-driver-core` version 3.6.3. I don't know if that's an internal snapshot of `mongodb-driver-core`, using the vertx version number of 3.6.3, or if that's actually the `mongodb-driver-core` version number of 3.6.3. Or possibly the version number for vertx is accidentally being reused for the `mongodb-driver-core` dependency.

The current version of `mongodb-driver-core` is 3.10.1. If you try to manually add that as a dependency to a vertx project, you get `java.lang.NoSuchMethodError` or similar, triggered by either vertx code or direct mongodb API code, due to having two incompatible ABIs in the classpath.

**Comment by karianna** [comment]
Thanks, Closed via #179 and #180
