### ISSUE TITLE
different databases

### ISSUE THREAD

**Issue by j040p3d20** [vert-x3/vertx-mongo-client#184]
I was using a vertx web app to make some spark calculations and write the results to mongo. The request contains a cfg object specifying were to write the results. I was seeing that even though i was creating clients with different cfg ( same server but different databases, same collection name ) i was sometimes getting results on the wrong database. It seems MongoClient.createShared is either misleading ( if you expect to receive a different data source name for different cfgs ) or working incorrectly ( if different cfgs should write in different dbs but end up writting in the same db because of the same default data source name  )

**Comment by karianna** [comment]
@j040p3d20 Can you provide an [SSCCE](http://sscce.org/)?

**Comment by karianna** [comment]
closing due to lack of response
