### ISSUE TITLE
`findOne` with invalid objectId hangs

### ISSUE THREAD

**Issue by jo5ef** [vert-x3/vertx-mongo-client#189]
When an invalid mongo object id is passed in the `query` to `findOne`, an "invalid objectid" exception is thrown and logged internally but the calling code has no way of catching it. The exception is neither bubbled up nor passed to the handler as a failed result.

Expected: `findOne` should throw an exception or call the handler with a failed result in case of illegal arguments.

The following test requires a running local mongo and does not complete:

```
@RunWith(VertxUnitRunner.class)
public class TestFindOne {

  @Test
  public void testFindOne(TestContext ctx) {
    var async = ctx.async();
    var vertx = Vertx.vertx();
    var db = MongoClient.createShared(vertx, new JsonObject()
      .put("db_name", "test"));

    try {
      db.findOne("test", new JsonObject().put("_id", new JsonObject()
          .put("$oid", "invalid")), new JsonObject(), r -> {
        async.complete();
      });
    } catch(Exception ex) {
      async.complete();
    }
  }
}
```

Log output:

```
java.lang.IllegalArgumentException: invalid hexadecimal representation of an ObjectId: [invalid]
  at org.bson.types.ObjectId.parseHexString(ObjectId.java:529)
  at org.bson.types.ObjectId.<init>(ObjectId.java:205)
  at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.writeObjectId(JsonObjectCodec.java:176)
  at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.writeValue(AbstractJsonCodec.java:129)
  at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.lambda$writeDocument$1(AbstractJsonCodec.java:261)
  at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.lambda$forEach$0(JsonObjectCodec.java:120)
  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.forEach(JsonObjectCodec.java:119)
...
```

**Comment by kostya05983** [comment]
@karianna I tried to figured out what happened. In mongo-core we have this,and mongo just log error.
` @Override
    public void onResult(final T result, final Throwable t) {
        try {
            wrapped.onResult(result, t);
        } catch (Throwable e) {
            logger.error("Callback onResult call produced an error", e);
        }
    }`
In our codec we can try catch exception something like this 
`
  @Override
  public void encode(BsonWriter writer, O value, EncoderContext encoderContext) {
    try {
      writeDocument(writer, null, value, encoderContext);
    } catch(IllegalArgumentException e) {
      e.printStackTrace();
    }
  }`
But encode is called by mongo functions. Also in jsonCodec we throw our exceptions but as I understand mongo will ignore them.
`
 @SuppressWarnings("unchecked")
  protected void writeValue(BsonWriter writer, String name, Object value, EncoderContext ctx) {
    BsonType type = getBsonType(value);
    if (type == null) {
      throw new IllegalStateException("Unknown BsonType for '" + value + "'");
    }
`
Do I understand something wrong?  Where do you think I can look?

**Comment by Bjiji** [comment]
Any news ? Any workaround so far ?

This is really worrisome that findOne does not return at all (nor a success or a failure). As you could imagine, this creates nasty problems as it break the execution flow of the application.

**Comment by rraks** [comment]
Is this still not resolved?

**Comment by karianna** [comment]
This has been fixed some time ago.
