### ISSUE TITLE
Find fails when reading object which contains an array with a null entry.

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-mongo-client#19]
The method `AbstractJsonObjectCodec.readArray` calls `JsonArray.add` to add new entries.  This causes a failure if the entry read is `null`.  In this case you need to use `addNull` to avoid an NPE.  See https://bugs.eclipse.org/bugs/show_bug.cgi?id=469553 for additional context.

**Comment by purplefox** [comment]
Fixed.

**Comment by sfitts** [comment]
Thanks
