### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid BSON field name $numberDecimal

### ISSUE THREAD

**Issue by razzbee** [vert-x3/vertx-mongo-client#196]
Try to store some decimal numeric data and I get this error :
java.lang.IllegalArgumentException: Invalid BSON field name $numberDecimal

**Comment by kostya05983** [comment]
@razzbee , I added numberDecimal to mongoClient.

**Comment by razzbee** [comment]
okay, thanks, will have a look again
