### ISSUE TITLE
iso 8601 is used for $date, but it lacks milliseconds support. 

### ISSUE THREAD

**Issue by ashertarno** [vert-x3/vertx-mongo-client#20]
the latest solution for $date handling leverages java.time.format.DateTimeFormatter.ISO_OFFSET_DATE_TIME (iso 8601) which doesn't support milliseconds. 
while dates in format  '2011-12-03T10:15:30+01:00' are accepted , attempt to send something like 
'2015-06-08T12:10:16.148+0300' throws parsing exception.

**Comment by pmlopes** [comment]
The current mongo client does properly parse millis the problem in your test case was that the string you provided is not valid according to the Java8 DateTime API, more specifically the timezone part is always expected to have a minute seperator HH:MM and HHMM is not valid
