### ISSUE TITLE
Custom SSLContext using a separate keystore supported?

### ISSUE THREAD

**Issue by alijaza** [vert-x3/vertx-mongo-client#208]
Hello, with the standard Java MongoClient, rather than changing global SSL/TLS settings, we can create a custom SSLContext and initialize it with a trusted certificate and key. Then we generate the SSLSocketFactory from it and provide it to the MongoClientOptions.Builder.

Is there some equivalent to this for the vertx-mongo-client? I don't see this in the documentation for JsonObject config...

**Comment by alijaza** [comment]
Something like this:

`
private static SSLContext createSSLContext() {
        try {
            SSLContext sslContext = SSLContext.getInstance("TLS");
            KeyManager[] keyManagers = getKeyManagers();
            sslContext.init(keyManagers, null, null);
            return sslContext;
        } catch (Exception e) {
            logger.error("Cannot create SSLContext", e);
        }
        return null;
    }

    private static KeyManager[] getKeyManagers()
            throws KeyStoreException, NoSuchAlgorithmException, IOException, CertificateException, UnrecoverableKeyException {

        try (InputStream inputStream = new FileInputStream(CERT_FILE)) {
            KeyStore clientKeyStore = KeyStore.getInstance("PKCS12");
            clientKeyStore.load(inputStream, AppConfig.TrMongoProperties.getKeystorePassword().toCharArray());

            KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509");
            kmf.init(clientKeyStore, AppConfig.TrMongoProperties.getKeystorePassword().toCharArray());
            return kmf.getKeyManagers();
        }
    }
`

And then something like this:

`            MongoClientOptions.Builder mco=MongoClientOptions.builder().socketFactory(createSSLContext().getSocketFactory());
`

**Comment by kostya05983** [comment]
Hello, @alijaza , No we don't have such options, because vertx mongoClient is multi platform. Default mongoClient allow to set SslContext from javax.net.ssl. But maybe we can add this. @vietj can we ignore some static methods from generation?. I think it's good to be provide static method which can be construct mongo instance from MongoClientSettings for java world.
