### ISSUE TITLE
ISODate type is serialized/deserialized incorrectly by vertx

### ISSUE THREAD

**Issue by rkrashr** [vert-x3/vertx-mongo-client#213]
java Date type is converted to json as {'$date': iso string}
and then passed to mongo client by looking for a string value matching '$date' key
and saves as long value into mongodb (not mongo ISODate type)

on the other hand, mongodb recognizes ISODate type in plain json as 
{'$date': long value}
or special Bson ISODate value construct.

The last one is not compatible with plain standard json, so the only option to create ISODate is to pass {'$date': long value}

It would be correct to change JsonObjectCodec to use long value instead of string value

**Comment by karianna** [comment]
This was fixed some time ago
