### ISSUE TITLE
value mentioned in documentation is wrong 

### ISSUE THREAD

**Issue by roottraveller** [vert-x3/vertx-mongo-client#225]
### Context

the value mentioned in the documentation is wrong 
```  
path -> io.vertx.ext.mongo.FindOptions


 /**
  * The default value of batchSize = 10.
  */
  public static final int DEFAULT_BATCH_SIZE = 20;
```

It should be `The default value of batchSize = 20.`
### version 
io.vertx:vertx-mongo-client:3.9.0

**Comment by DarwinsBuddy** [comment]
Should be fixed in https://github.com/vert-x3/vertx-mongo-client/pull/273
