### ISSUE TITLE
Groovy: update converts inner map/list to JsonObject/JsonArray

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-mongo-client#24]
In the Mongo client API update has the side effect of reserializing the updated data from the DB in place.  This means that the interior property values are repopulated via the installed Codec which in our case means that they are recreated as JsonObject/JsonArray instances.  In the case of select we explicitly convert the objects using `InternalHelper.wrapObject`, but that doesn't happen in the update case.  Fixing this may be a bit tricky as the conversion needs to occur after the operation has completed, but the update callback doesn't have access to the orignally updated object.  I think this will invovle wrapping the supplied handler with one that has access to the original object and can perform the wrap call.  However, I'm not sure that the code generator is capable of expressing this (not to mention the fact that this is specific to the way the mongo API works, so we may not want to do this generally).

I'll work up a gist which demonstrates the issue.

**Comment by sfitts** [comment]
As I suspected this happens on insert too (and probably replace and save).  I'll have a gist soon to demonstrate all these cases (have to duck out now so it will be a couple of hours).

**Comment by sfitts** [comment]
The following gist demonstrates the issue for insert and update.  I'm pretty sure that save and replace will have the same issues -- https://gist.github.com/sfitts/af7c6446e8ba709ffcfc.

**Comment by purplefox** [comment]
>> In the Mongo client API update has the side effect of reserializing the updated data from the DB in place

What's the reason for doing this?

**Comment by sfitts** [comment]
No idea.  It happens in the Mongo java driver so you'd have to ask the MongoDB folk.

**Comment by purplefox** [comment]
Ok, I guess I have misunderstood what you meant then. Could you maybe explain in a bit more detail what you mean by "update has the side effect of reserializing the updated data from the DB in place. "

**Comment by purplefox** [comment]
I think what you're saying is that the object you pass into insert, for some reason, gets updated - so my question is - what's the reason for this? If there is no good reason  we can easily prevent it from happening, after all its our own object.

**Comment by sfitts** [comment]
It's probably easiest to see/understand via the gist I posted, but I'll give it my best shot.  Let's say you have the following JSON object defined in groovy:

```
      def obj = [prop1: ['this', 'that'], prop2: [inner: 'peace']]
```

Now lets say you issue the following call to the Vertx mongo client (again in groovy):

```
      mongo.insert('test', obj) { result ->
        ... do some stuff on completion...
      }
```

When the operation completes you'd expect `obj` to still be a legal groovy JSON object (that is all maps and lists as normal), but instead `prop1` is now a JsonArray and `prop2` is now a JsonObject.  Since JsonArray doesn't implement List and JsonObject doesn't implement Map the object is essentially unusable by the rest of the groovy code.

Note that the same problem does not occur when you use the Java driver directly due to the way that it is configured by default.  So if you ran my gist using the async Java driver all the the verifcation calls would return `true` (as expected).

**Comment by purplefox** [comment]
Ok thanks Sean, I get that that is what is happening, but the question is _why_ ?

**Comment by sfitts** [comment]
You are correct, the object gets updated.  If it is an insert the `_id` property will be added and all of the other properties will be recreated via the registered Codec's.  The code that does this is inside the Java async driver and I know of no way to prevent it from happening.

**Comment by purplefox** [comment]
Updating a generated id seems valid but I don't see why any other updates are done.

I don't buy the argument (yet!) that the code is "inside the async driver". Surely this is handled by the JsonObjectCodec (our code)?

I'm not an expert on this code but I can see a method called "generateIdIfAbsentFromDocument" which seems to insert the id. So, can't we control the behaviour in the codec class?

**Comment by sfitts** [comment]
Perhaps.  Though we may find it difficult to understand the context in which we are being asked to operate.  The creation of the JsonObject and JsonArray intances is clearly being done by our codec.  But the codec code is simple -- you say read this Bson and it does so and produces the objects it thinks it should.  Getting it to produce something different here sounds... difficult.

Not to mention that when this code is running the pure Java case it is doing exactly the right thing.  It is only the fact that we are passing through the groovy shim that causes it to be wrong.  So I think the adjustment has to occur this as well.  Or am I missing something?

**Comment by purplefox** [comment]
A simple solution would be to make a copy of our json object before passing it to Mongo, then when we get the result back just take the generated id field (if any) and stick it back in the original object....

But I would love to know why Mongo client is regenerating the entire object when just an id is updated - it seems horribly inefficient...

**Comment by sfitts** [comment]
OK, so I just debugged into this and here is what I see.  The conversion of the graph is happening as a side-effect of doing the write (as I suspected), but it isn't directly due to the mongo driver (as you suspected).  During the encoding of the object graph we have to iterate each of the sub-graphs.  Since the outermost object here is a JsonObject (created as we pass through the groovy shim) the code that does this is `JsonObject.Iter.next()` (at line 813 in JsonObject.java).  If this routine sees either a Map or a List (which it will in this case) it not only returns that in the Map entry it also updates JsonObject itself as a side effect.

So in the end it is completely due to code that Vertx controls.  My bad for assuming it was the Mongo codec that was doing this.  Any thoughts on how we might fix this?

**Comment by sfitts** [comment]
FWIW, the mongo codec is the entry point here, maybe we can use that to our advantage.  Here's the full stack at the point where the object is initially altered:

```
JsonObject$Iter.next() line: 799	
JsonObject(Iterable<T>).forEach(Consumer<? super T>) line: 74	
JsonObjectCodec.forEach(JsonObject, BiConsumer<String,Object>) line: 96	
JsonObjectCodec.forEach(Object, BiConsumer) line: 28	
JsonObjectCodec(AbstractJsonCodec<O,A>).writeDocument(BsonWriter, String, Object, EncoderContext) line: 252	
JsonObjectCodec(AbstractJsonCodec<O,A>).encode(BsonWriter, O, EncoderContext) line: 28	
BsonDocumentWrapperCodec.encode(BsonWriter, BsonDocumentWrapper, EncoderContext) line: 63	
BsonDocumentWrapperCodec.encode(BsonWriter, Object, EncoderContext) line: 29	
InsertCommandMessage.writeTheWrites(BsonOutput, int, BsonBinaryWriter) line: 99	
```

Maybe we could provide a variant of the iterator that didn't update the object which we could use in this case?

**Comment by purplefox** [comment]
Right, the iterator shouldn't change the JsonObject, in fact I fixed this bug some time back but it got reverted when Julien's changes to JsonObject to solve the Groovy wrapper issue were reverted :(

**Comment by sfitts** [comment]
Cool -- since that's in core I'll leave it to you ;).  Thanks for the help.

**Comment by purplefox** [comment]
I'll fix it in core, but if you could write a test for the mongo client which tests this case, that would be great :)

**Comment by sfitts** [comment]
Will do.  I'll put a PR up a bit later today.

**Comment by purplefox** [comment]
Actually, no need to worry, I've fixed it in core and added a test in mongo client too.

**Comment by sfitts** [comment]
Confirmed fix with my previously posted gist.  Thanks.
