### ISSUE TITLE
Config Parsing is out of order

### ISSUE THREAD

**Issue by DarrinProtag** [vert-x3/vertx-mongo-client#243]
### Version

4.0.0

### Context

I was parsing json/JsonObject with MongoClientOptionsParser.

### Steps to reproduce

1.            var parsing : MongoClientOptionsParser = MongoClientOptionsParser(vertx, JsonObject(mongoConfigJson))
2. Input Json: core: {
  mongo:{
    db_name: "mydb"
    connection_string: "mongodb://localhost:27017"
    maxPoolSize: 10
    minPoolSize: 3
  }
}
3. maxPoolSize is ignored.

### Extra

The source code below, only considers connection_string. It should almost certainly parse all the other values *first*, then apply the connection_string. That would allow one to set individual values in a readable way. While overriding them with values from the connection_string. I guess you could just remove the else, and allow the individual settings to override anything parsed from the connection_string.

But, as-is, you can't really have connection_string *and* any other settings.

  public ConnectionPoolSettingsParser(ConnectionString connectionString, JsonObject config) {
    ConnectionPoolSettings.Builder settings = ConnectionPoolSettings.builder();
    if (connectionString != null) {
      settings.applyConnectionString(connectionString);
    } else {
      Integer maxPoolSize = config.getInteger("maxPoolSize");
      if (maxPoolSize != null) {
        settings.maxSize(maxPoolSize);
      }

**Comment by vietj** [comment]
so we should first apply the connection string and then other options, is that right ?

**Comment by DarrinProtag** [comment]
> so we should first apply the connection string and then other options, is that right ?

Yes. That's what I think would be most intuitive. I'd expect the explicit options to overwrite anything from the connection string.

If you find some reason to do it in the opposite order, I could live with that too. The most important thing to fix is that both sources are combined and applied (right now, one is ignored).

**Comment by vietj** [comment]
I believe we are sharing the same opinion, but it would be good to hear more voices here

**Comment by vietj** [comment]
@DarrinProtag can you provide a pull request with this changes and tests ?

**Comment by tsegismont** [comment]
@vietj @DarrinProtag the [documentation](https://github.com/vert-x3/vertx-mongo-client/blob/83afa4913f924a0b26b32fb33af06b5e0a288411/src/main/asciidoc/index.adoc#configuring-the-client) indicates that the client is configured either by the connection string or the options.

I'm not sure why this decision was made, perhaps @karianna or @johnoliver know?

In any case, I don't believe we should change that behavior in a micro version.

@vietj I agree that we can do this improvement but perhaps 4.1 is a better target.

**Comment by karianna** [comment]
> @vietj @DarrinProtag the [documentation](https://github.com/vert-x3/vertx-mongo-client/blob/83afa4913f924a0b26b32fb33af06b5e0a288411/src/main/asciidoc/index.adoc#configuring-the-client) indicates that the client is configured either by the connection string or the options.
> 
> I'm not sure why this decision was made, perhaps @karianna or @johnoliver know?
> 
> In any case, I don't believe we should change that behavior in a micro version.
> 
> @vietj I agree that we can do this improvement but perhaps 4.1 is a better target.

Before we even became maintainers and we stepped down some time ago so we haven't been keeping up I'm afraid :-(

**Comment by vietj** [comment]
yes this is a good target for 4.1 although it looks like a quick-win.
