### ISSUE TITLE
MongoClientOptionsParser does not use credentials in connection_string

### ISSUE THREAD

**Issue by mf81bln** [vert-x3/vertx-mongo-client#248]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version

Which version(s) did you encounter this bug ?
- v4.0.0

### Context

Spring Boot Starter Data MongoDB allows to create a connection just by providing a proper MongoDB connection string.
From a first glance the vert.x `MongoClientOptionsParser` seems to do the same.

But it actually ignores credentials, see:
https://github.com/vert-x3/vertx-mongo-client/blob/master/src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java#L52

Credentials are fetched from `config`, not from the already parsed `ConnectionString`

Since it's official standard to put credentials in the connection string, I think this should work and would call it a bug.
```
mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
```
see: https://docs.mongodb.com/manual/reference/connection-string/

### Do you have a reproducer?

I'm using it in a private repo, but based on the description above it should be easy to understand.

### Extra

Maybe related: #243 

If this was deliberately not implemented, for example for security reasons...
> Developers should be aware that the contents of the password component may be sensitive, and they should avoid leaking it (e.g. the full URI should not appear in exception messages or log records, which might be visible to less privileged personnel).

...I think it should at least be mentioned in the documentation.

**Comment by vietj** [comment]
I think it would be good to implement this
