### ISSUE TITLE
Cannot upsert document with save() vertx 3.0.0

### ISSUE THREAD

**Issue by kishorgandham** [vert-x3/vertx-mongo-client#25]
Hi,

It looks like the save() method is not inserting document is the _id is populated and a document with such  id doesnt exist in mongodb. 

Sample code to replicate

import io.vertx.ext.mongo.MongoClient;
import io.vertx.core.json.JsonObject;
import io.vertx.core.AbstractVerticle;

public class Server extends AbstractVerticle {

public void start() {

    JsonObject config = new JsonObject();
    config.put("host", "127.0.0.1");
    config.put("port", 27017);
    config.put("db_name", "bug_test");
    MongoClient client = MongoClient.createShared(vertx, config);
    JsonObject document = new JsonObject().put("title", "The Hobbit");
    document.put("_id", 123456);

    //insert() works. save() is not working
    client.save("bug_test", document, res -> {
        if (res.succeeded()) {
            String id = res.result();
            System.out.println("Inserted with id " + id);
        } else {
            res.cause().printStackTrace();
        }
    });
}
}

**Comment by pmlopes** [comment]
The issue is related to the way the mongo driver works, if you want to do upserts you should do instead:

```
      // test case
      JsonObject query = new JsonObject().put("_id", 123456);

      JsonObject doc = new JsonObject().put("title", "The Hobbit");
      doc.put("_id", 123456);

      mongoClient.replaceWithOptions(collection, query, doc, new UpdateOptions().setUpsert(true), r -> {
        // in this case the id will always be null because it is a custom ID not a mongo generated one
        mongoClient.find(collection, new JsonObject().put("_id", 123456), f -> {
           // this will succeed and you will have 1 result
        }));
      }));
```
