### ISSUE TITLE
Update MongoDB driver to 3.12.8

### ISSUE THREAD

**Issue by sophokles73** [vert-x3/vertx-mongo-client#259]
The MongoDB driver used in the pre-4.x vert-x versions is quite outdated (3.10.1) and should probably be updated to the latest 3.12.8 service release to take advantage of bug fixes and new features.

I can create a corresponding PR if you agree that we should update the driver.
However, I am not sure if there actually will be a vert-x 3.9.9 release which could include this change ...

**Comment by vietj** [comment]
@sophokles73 please shoot PRs for master, 4.1 branch and 3.9 branch, there is a 3.9.9 expected. Actually Vert.x 3 remains supported for 2 years starting from the 4.0 release
