### ISSUE TITLE
ObjectId support

### ISSUE THREAD

**Issue by wieki** [vert-x3/vertx-mongo-client#28]
ObjectId support seems still basic in the 3.0.0 implementation, I noticed that conversion in the codec is still a todo. The behavior is now not completly consistent, a date value is (like with Mongo tools) is converted to a { "$date" : "dat-val"} value, while the objectIds are converted to the hex string values, instead of a more consistent { "$oid" : "id-val" } value. 

I made some small adjustments to enable ObjectId support, but it has an important issue. The result callbacks have to switch to a JsonObject return type, instead of a more generic String, since the code generator will not allow for a generic Object which you could check afterwards. But an important advantage is that ObjectIds can be properly used (certainly with existing Mongo databases).

**Comment by pmlopes** [comment]
There was a PR just merged about OIDs could you please retest and report if this is working for you? Thanks!

**Comment by karianna** [comment]
@wieki Could you restest this on master and let us know?

**Comment by karianna** [comment]
@pmlopes - Apologies for jumping over your comments - figured I'd add the OP username

**Comment by cescoffier** [comment]
Any news on this ? Should it be delayed to 3.2.0 ?

**Comment by karianna** [comment]
I'll probably push all 3.1.0 issues to 3.2.0 at this stage.

**Comment by johnoliver** [comment]
you can push the bug to 3.2.0 on the basis that it is now just a question for the OP, but I believe the original bug is resolved. We are using the current snapshots and object Id's and it appears to be working well.

**Comment by karianna** [comment]
Back to 3.1.0 and closed then,

**Comment by wieki** [comment]
I'm sorry I couldn't reply earlier, I am no longer part of the project that
involved vertx, I wasn't available earlier to comment.

2015-09-14 12:58 GMT+02:00 Martijn Verburg <notifications@github.com>:
