### ISSUE TITLE
the generated default _id value type is string, not ObjectId ?

### ISSUE THREAD

**Issue by darrenweb** [vert-x3/vertx-mongo-client#302]
When saving data to db, the generated default _id value type is string, not ObjectId.
Did you design this on purpose? Or is it a bug?
Below is my code.
------------------------------------------------------------------
 mongoClient.save("test", new JsonObject().put("v", "vertx"), mongo -> {});
------------------------------------------------------------------
![20230428171836](https://user-images.githubusercontent.com/4675382/235094313-7db46c97-534b-494e-b4c7-be61a8734ae8.png)

**Comment by tsegismont** [comment]
Most probably the client is configured with `useObjectId` set to `true`.

See https://vertx.io/docs/vertx-mongo-client/java/#_configuring_the_client
