### ISSUE TITLE
Support for indexes

### ISSUE THREAD

**Issue by michel-kraemer** [vert-x3/vertx-mongo-client#31]
It would be great if the client would support managing indexes (`getIndexes()`, `createIndex()` and `dropIndex()`, and maybe even `ensureIndex()`). Any plan to implement this?

**Comment by etorres** [comment]
Instead, I would rather ask the question more generally: is there any plan to support all the operations of the interface MongoCollection of the mongoDB Java driver:

http://api.mongodb.org/java/3.0/com/mongodb/client/MongoCollection.html

Otherwise, the client might fail to cover a large number of mongoDB use cases.

**Comment by pmlopes** [comment]
Hi you should be looking at this class instead: http://api.mongodb.org/java/3.0/com/mongodb/async/client/MongoCollection.html

It regards to covering the whole API it is just a matter of having time for it or someone from the community to provide PRs, it does not to be the whole API at once though :)

**Comment by etorres** [comment]
Sorry, I don't get the point. I suppose that your objective with vertx-mongo-client is to provide a replacement for mongoDB Java driver by building a Vert.x wrapper around the collection's operations, but this seems not to be the case. Could you clarify this for me, please. Thanks!

**Comment by pmlopes** [comment]
You asked if we would cover the driver API, i just linked the async driver API because we use the async driver (not the one you linked).

We are not replacing the driver, in fact the vertx-mongo-client uses the async driver internally. Of course we cannot just expose that class since we need to create as you said a vert.x wrapper, so we can be polyglot.

**Comment by etorres** [comment]
Many thanks for your response. Now I see the difference with the async driver. As I said before, it's very unlikely that someone could use solely the vertx-mongo-client if it lacks support for common operations, such as managing collection indexes. I look forward to this project continuing to improve and I promise that if I manage to get some free time, I will contribute to the project.

**Comment by meggarr** [comment]
Probably, I would suggest this is not necessary, since createIndex can be achieved simply by `MongoClient.runCommand`, e.g.

```
mongoClient.runCommand("createIndexes",
        new JsonObject()
            .put("createIndexes", <collection-name>)
            .put("indexes", new JsonArray()
                .add(new JsonObject().put("name", "field1_field2_idx")
                    .put("key", new JsonObject()
                        .put(field1, 1).put(field2, 1))
                    .put("unique", true)
                    .put("sparse", true))
                .add(new JsonObject().put("name", "login_hashed_token_idx1")
                    .put("key", new JsonObject()
                        .put(loginTokensField + "." + hashedTokenField, 1))
                    .put("sparse", true))
                .add(new JsonObject().put("name", "field_sub-field_idx")
                    .put("key", new JsonObject()
                        .put(field + "." + sub-field, 1))
                    .put("sparse", true))),
        cr -> {
          if (cr.succeeded()) {
            JsonObject result = cr.result();
            log.info("CreateIndexes succeeded result >" + result.encodePrettily());
          } else {
            log.warn("CreateIndexes failed", cr.cause());
          }
        });
```

**Comment by karianna** [comment]
I'll leave it in the backlog but PRs are welcome, I favour the client modelling the domain with its API as opposed to the generic runCommand fallback.  Appreciate it's a perfectly valid workaround though.

**Comment by lujop** [comment]
In the meantime it will be good to have a way to retrieve driver MongoClient object, at least expose it in MongoclientImpl.
