### ISSUE TITLE
Save method does not insert a new document when the _id field is specified

### ISSUE THREAD

**Issue by joselillo** [vert-x3/vertx-mongo-client#32]
When I try to insert a new document specifiying the _id field, the document will not be saved.

document = {
        "title": "New document",
        "_id": "12345"
    }
mongoClient.save("collectionName", document, callback);

upsert default value is false, and the mongoClient.save method calls replaceOne because the id is not null, and replaceOne will create a UpdateOption object without arguments => upsert is false => the document will not be created.

Thanks.

**Comment by kajmagnus79** [comment]
I too was surprised by this. In the end I changed from `mongoClient.save(...)` to `client.insert(...)`.

**Comment by pmlopes** [comment]
You should look at the mongo-async-driver API:
http://mongodb.github.io/mongo-java-driver/3.0/driver-async/

and not really think of the mongo cli API since the client is built on top of the async driver.

**Comment by karianna** [comment]
If the API is 'correct' then this is perhap a documentation issue.  I'll need to double check with those more hands on than I.

**Comment by karianna** [comment]
Hmm reading the other issues it seems that many end users aren't aware that we're using the async driver internally.  I'll raise a seperate doc / javadoc issue

**Comment by karianna** [comment]
Closing for new - see https://github.com/vert-x3/vertx-mongo-client/issues/37
