### ISSUE TITLE
useObjectId Doesn't work

### ISSUE THREAD

**Issue by diabolicallab** [vert-x3/vertx-mongo-client#36]
Setting useObjectId to true in the configuration results in the _id being saved as a hex string rather than an ObjectId.

**Comment by pmlopes** [comment]
There was a PR about ObjectIds just merged could you re-test this issue and report the status?

**Comment by karianna** [comment]
@diabolicallab Are you able to retest this on master?

**Comment by diabolicallab** [comment]
I tested on master after the PRs and it still doesn't work. I already created a branch in my fork for the fix. I should have a tested PR for you today.

**Comment by karianna** [comment]
Fantastic thank you!

On Friday, 28 August 2015, diabolicallab <notifications@github.com> wrote:

> I tested on master after the PRs and it still doesn't work. I already
> created a branch in my fork for the fix. I should have a tested PR for you
> today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vert-x3/vertx-mongo-client/issues/36#issuecomment-135851753>
> .
>


-- 
Cheers, Martijn (Sent from Gmail Mobile)

**Comment by karianna** [comment]
I've assigned to me for review when it comes in (since I can't assign to OP)

**Comment by diabolicallab** [comment]
Martijn, The PR has been submitted.

**Comment by johnoliver** [comment]
Should have been fixed by #38
