### ISSUE TITLE
Add Documentation / Javadoc making it clear that this client uses the Mongo Async Driver

### ISSUE THREAD

**Issue by karianna** [vert-x3/vertx-mongo-client#37]

**Comment by karianna** [comment]
May need to open an issue on the vertx-web project.

**Comment by cescoffier** [comment]
Why is this related to vertx-web ? The documentation and javadoc are generated in the vertx-mongo-client. (maybe I miss something obvious)

**Comment by karianna** [comment]
Hi Clement,

My misunderstanding I suspect

On Sunday, 30 August 2015, Clement Escoffier <notifications@github.com>
wrote:

> Why is this related to vertx-web ? The documentation and javadoc are
> generated in the vertx-mongo-client. (maybe I miss something obvious)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vert-x3/vertx-mongo-client/issues/37#issuecomment-136093146>
> .
>


-- 
Cheers, Martijn (Sent from Gmail Mobile)
