### ISSUE TITLE
Stop throwing away useful results from Mongo

### ISSUE THREAD

**Issue by johnoliver** [vert-x3/vertx-mongo-client#40]
A number of the operations such as update and replace throw away useful info by taking the UpdateResult (or whatever), throwing it away then returning null. Such as at:

https://github.com/vert-x3/vertx-mongo-client/blob/master/vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java#L153

**Comment by karianna** [comment]
I'd argue that's breaking the intent of wrapping that driver, so labelling as a bug.  PRs welcome!

**Comment by zdila** [comment]
Isn't this a duplicate of #2 ?

**Comment by karianna** [comment]
Very close to it, they could be merged probably. Doing so now...
