### ISSUE TITLE
JAVA high frequent gc - com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler EATs CPU

### ISSUE THREAD

**Issue by Kenjee** [vert-x3/vertx-mongo-client#42]
i found a bug using "io.vertx.ext.mongo.MongoClient". If MongoDB is unavailable for a minute or less a minute the VertxInstance runs into many small GCs and eats CPU.  While MongoDB is back only restart helps.

![mongoeatingcpu](https://cloud.githubusercontent.com/assets/4869328/10047731/c9fa4156-620f-11e5-8f68-b2c40f20590b.png)

while profiling this problem locally i found "com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler" causing the GCs and this uses up to 40% CPU usage. Before disconnection CPU usage was near 0% because i only read periodic from empty mongodb.

*TestCase:*
MongoClient client = MongoClient.createShared(vertx, this.mongoConfig);
// config is: {"mongo": {"host": "127.0.0.1","port": 27017,"db_name": "notification"}}
Verticle start contains
"this.timerID = vertx.setPeriodic(TimeUtils.MINUTE_IN_MILLISECONDS, INotificationHandler.create(vertx, config()));" and handler reads data by using client

*seems to be a problem with*
* Issues for mongoDB Java Driver
* https://jira.mongodb.org/browse/JAVA-1881
* https://jira.mongodb.org/browse/JAVA-1825
* should be fixed with version 3.0.3, 3.1.0 

*Possible Solution* 
* upgrade the dependencies  for http://mvnrepository.com/artifact/org.mongodb/mongodb-driver-async
* groupId: org.mongodb
* artifactId: mongodb-driver-async
* version: newest

**Comment by karianna** [comment]
Seems like a simple enough fix - PRs welcome!
