### ISSUE TITLE
Creating a new document with an _id field fails

### ISSUE THREAD

**Issue by johnoliver** [vert-x3/vertx-mongo-client#44]
The current logic of saveWithOptions, says that if the document to save has an _id then the query gets changed to a "replaceOne", if the db then does not have an existing entry with that _id no document will be saved.

**Comment by karianna** [comment]
That begs the question, what should the logic say?

**Comment by johnoliver** [comment]
willing to bet passing `new UpdateOptions().upsert(true)" to replaceOne would do the trick
