### ISSUE TITLE
Check that ObjectId convertion is applied to all objects that it should apply to

### ISSUE THREAD

**Issue by johnoliver** [vert-x3/vertx-mongo-client#45]
Go through all of the methods in MongoClientImpl, as I think there are some objects that should have encodeKeyWhenUseObjectId called on them that currently do not, updateWithOptions for instance does not call it on the update, which I believe means you cant pass in an object to update with an ObjectId type _id.

**Comment by llfbandit** [comment]
Queries are now wrapped, so all queries should be independent of using the useObjectId property or not,
I've added decoding on find method to reflect the insert method.
**All is still compatible with previous versions except the decoding as we now always unwrap the _id field.**
Small performance improvements to encode / decode methods.

**Comment by karianna** [comment]
I'll let @johnoliver close this if he's happy with the PR, We'll have to note the decoding as a potentially breaking change, but that's OK as the 3.4.0 release train will have a section for that.
