### ISSUE TITLE
support user defined document id

### ISSUE THREAD

**Issue by michaelom** [vert-x3/vertx-mongo-client#5]
I want to persist domain objects to MongoDb overriding the name of the ID_FIELD from "_id to a domain object specific property (e.g. "customerId"). My current workaround looks like this:

```
    public Observable<Customer> addCustomer(Customer customer) {
        JsonObject document = customer.toJson().put("_id", customer.getId().toValue());
        return mongoService.insert(collection, document);
    }
```

**Comment by purplefox** [comment]
Seems reasonable. How about submitting a PR? :)

**Comment by michaelom** [comment]
Hi Tim,

submitting a PR sound reasonable too. ;-)
I will think about a reasonable way to supply user defined ID fields first and propose a solution here.

**Comment by xunitc** [comment]
Hi.
I want save a document with java.lang.Long _id, and get this exception:
io.vertx.core.eventbus.ReplyException: java.lang.Long cannot be cast to java.lang.CharSequence
	at io.vertx.core.eventbus.impl.MessageImpl.fail(MessageImpl.java:288)

I am not sure it is a mongo-service problem or a json problem. but my db use Long _id.

**Comment by xunitc** [comment]
Hi, at the line 106 of io.vertx.ext.mongo.impl.MongoServiceImpl.java
I see
        return document.getString(ID_FIELD);
I think maybe some one's _id type is not String, so is it better to use 
        return document.getValue(ID_FIELD);

**Comment by purplefox** [comment]
Thanks! Could you send a PR with a test?

**Comment by purplefox** [comment]
I think this is fixed now in master. If not, please reopen
