### ISSUE TITLE
AbstractJsonCodec throws UnsupportedOperationException when reading timestamps

### ISSUE THREAD

**Issue by wklenk** [vert-x3/vertx-mongo-client#51]
Using the vertx-mongo-client in a MongoDB using replica sets, in some come database operations I get a *java.lang.UnsupportedOperationException*.
The reason seems to be that the replica set returns a date (or timestamp) and non-replicated doesn't. It seems that Vertx BSON support can't handle date types yet. The parser isn't complete and so returns an *java.lang.UnsupportedOperationException*.

Example stack trace:

> java.lang.UnsupportedOperationException
>        at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.readTimeStamp(AbstractJsonCodec.java:387)
>        at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.readValue(AbstractJsonCodec.java:71)
>        at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.readDocument(AbstractJsonCodec.java:230)
>        at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.decode(AbstractJsonCodec.java:23)
>        at com.mongodb.connection.CommandResultCallback.callCallback(CommandResultCallback.java:54)
>        at com.mongodb.connection.CommandResultCallback.callCallback(CommandResultCallback.java:29)
>        at com.mongodb.connection.CommandResultBaseCallback.callCallback(CommandResultBaseCallback.java:39)
>        at com.mongodb.connection.ResponseCallback.onResult(ResponseCallback.java:48)
>        at com.mongodb.connection.ResponseCallback.onResult(ResponseCallback.java:23)
>        at com.mongodb.connection.DefaultConnectionPool$PooledConnection$2.onResult(DefaultConnectionPool.java:446)
>        at com.mongodb.connection.DefaultConnectionPool$PooledConnection$2.onResult(DefaultConnectionPool.java:440)

**Comment by MazizEsa** [comment]
Hi all. Will take a shot on this issue. Will try to implement the TimeStamp.
