### ISSUE TITLE
Result handlers not run on calling vertx context

### ISSUE THREAD

**Issue by gokl** [vert-x3/vertx-mongo-client#52]
Hi,

it seems to me that the result handlers for the several methods in MongoClient.java / MongoClientImpl.java are not being run on the context of the calling thread, i.e. the eventloop.

Instead the call to vertx.runOnContext creates a new context for the thread the result handler runs in (mongo client threads). This causes the result handlers to run on a different thread than the verticles eventloop and makes the handlers run in parallel.

Is this wanted behavior? It caused me some race condition headache because i thought the result handlers would run on the same eventloop (and thread)..

A solution would be to save the context of the calling thread via vertx.getOrCreateContext() and use that context for runOnContext() in the several result handler wrappers.

**Comment by purplefox** [comment]
It looks like a bug to me.

You're right: The context should be captured before the call and context.runOnContext() should be used to execute the callback.

**Comment by gokl** [comment]
Ok, should i create a pull request for it or do you want to fix it?

**Comment by purplefox** [comment]
I'm not the maintainer of this component, but I'm sure he won't a PR ;)

**Comment by karianna** [comment]
PR most welcome!

**Comment by purplefox** [comment]
PR here https://github.com/vert-x3/vertx-mongo-client/pull/57
