### ISSUE TITLE
Fix flapdoodle classnotfound exceptions in build 612 and 613

### ISSUE THREAD

**Issue by karianna** [vert-x3/vertx-mongo-client#54]
Build failures: https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-mongo-client/612/console

**Comment by cescoffier** [comment]
Hi Martin,

It's a change I made to avoid important more tan one version of slf4j. Will fix it this morning.

**Comment by karianna** [comment]
Thanks!
