### ISSUE TITLE
Markdown conversion in vertx-mongo-client docs is broken

### ISSUE THREAD

**Issue by lukehutch** [vert-x3/vertx-mongo-client#62]
Markdown conversion for [http://vertx.io/docs/vertx-mongo-client/java/](http://vertx.io/docs/vertx-mongo-client/java/) somehow gets broken halfway through, and doesn't recover.

**Comment by karianna** [comment]
Need to figure out if this something we fix in this project or elsewhere...

**Comment by cescoffier** [comment]
Oh sorry, I've already fixed it. 
It will be redeploy with the 3.2.1 release.
