### ISSUE TITLE
i can't find gridfs support

### ISSUE THREAD

**Issue by thinktkj** [vert-x3/vertx-mongo-client#83]
i can't find gridfs support

**Comment by karianna** [comment]
@thinktkj - Can you elaborate a bit further as to what functionality in the driver you're expecting to be exposed?

**Comment by thinktkj** [comment]
MongoClientImpl.java  && MongoClient.java

add one method like this:

`@Override
	public io.vertx.ext.mongo.MongoClient findGridFsBuffer(String collection, ObjectId objectId, AsyncOutputStream outputStream, Handler<AsyncResult<Long>> resultHandler) {
		requireNonNull(collection, "collection cannot be null");
		requireNonNull(resultHandler, "resultHandler cannot be null");

		GridFSBucket gridFSBucket = GridFSBuckets.create(holder.db, collection);

		gridFSBucket.downloadToStream(objectId, outputStream, new SingleResultCallback<Long>() {
			@Override
			public void onResult(Long result, Throwable t) {
				if (result == null || t != null) {
					resultHandler.handle(Future.failedFuture(t));
				} else {
					resultHandler.handle(Future.succeededFuture(result));
				}
			}

		});

		return this;
	}`

**Comment by karianna** [comment]
@thinktkj - Thanks - I've set this to Pull Requests welcome (we're tackling a few other things at present) :-)

**Comment by diabolicallabs** [comment]
I'm working on this in https://github.com/diabolicallabs/vertx-mongo-client Hope to have something working properly by 8 Jan 2017.

**Comment by vietj** [comment]
@diabolicallabs any news about this contribution ?

**Comment by diabolicallabs** [comment]
Hi Julien,
The code is done and tested. Only the docs are left.  I'll finish that in
the next days.

Are you going to Summit?

**Comment by vietj** [comment]
great!

unfortunately my proposal has been refused... so not going!

**Comment by diabolicallabs** [comment]
Still working on this. Whilst doing the documentation I realized that up/downloading of buffers could be simplified. So, I'm making that change and testing.

**Comment by vietj** [comment]
good to know it's in progress, perhaps it oculd make it to 3.4.2 ?

**Comment by diabolicallabs** [comment]
Yes. That is the goal.

**Comment by diabolicallabs** [comment]
Finishing the last examples of Gridfs. Will complete PR by EOD May 16 Hawai`i time.

**Comment by vietj** [comment]
nice, expect a review, it shall be in 3.4.2 hopefully
