### ISSUE TITLE
Save object with _id null should generate one automatically?

### ISSUE THREAD

**Issue by kennedyoliveira** [vert-x3/vertx-mongo-client#91]
Hello,

i'm trying vertx for a real project, and it's my first time using mongo db, so maybe i'm asking something noob, but anyway, i'm currently using java in my project, in a save, i first convert the request to a pojo, do some validations on the pojo, and if everything is OK i then save it with mongoClient.save, the problem is, my pojo has a field `_id` that 'll be the mongo id, but since it's null and the code only check if it's null not if the key exists, it send to mongo as null and then save as null, instead of not sending or generating automatically.

I noticed this behavior is in this piece of code, from the cliente:
```
@Override
public io.vertx.ext.mongo.MongoClient saveWithOptions(String collection, JsonObject document, WriteOption writeOption, Handler<AsyncResult<String>> resultHandler) {
  requireNonNull(collection, "collection cannot be null");
  requireNonNull(document, "document cannot be null");
  requireNonNull(resultHandler, "resultHandler cannot be null");

  MongoCollection<JsonObject> coll = getCollection(collection, writeOption);
  Object id = document.getValue(ID_FIELD);
  if (id == null) {
    coll.insertOne(document, convertCallback(resultHandler, wr -> useObjectId ? document.getJsonObject(ID_FIELD).getString(JsonObjectCodec.OID_FIELD) : document.getString(ID_FIELD)));
  } else {
    JsonObject filter = new JsonObject();
    JsonObject encodedDocument = encodeKeyWhenUseObjectId(document);
    filter.put(ID_FIELD, encodedDocument.getValue(ID_FIELD));

    com.mongodb.client.model.UpdateOptions updateOptions = new com.mongodb.client.model.UpdateOptions()
        .upsert(true);

    coll.replaceOne(wrap(filter), encodedDocument, updateOptions, convertCallback(resultHandler, result -> null));
  }
  return this;
}
```

It do a `Object id = document.getValue(ID_FIELD);` but don't check if the key `ID_FIELD` exists, i know i can generate an ID and set it, but i think this should be handled out of the box by the mongoClient, like checking if the key exists and then checking if it's null, if the key exists and is null then it should be removed or autogenerated.

What you guys think? I'm doing something that i shouldn't? I could send a PR improving it if is suitable, or if there's a simple alternative i would like to know.

Thanks in advance,
Kennedy Oliveira

**Comment by karianna** [comment]
Are you using the async driver?

**Comment by kennedyoliveira** [comment]
@karianna I'm using the one is available, vertx Mongo client with Async callbacks, I guess yes, theres another one or something?

The piece of code I got from the source of vertx mongo client

**Comment by karianna** [comment]
So I think the behaviour is as intended, if you do not specify `ID_FIELD` and/or `document.getValue(ID_FIELD);` returns null then the Vertx Mongo client inserts the document and gets the generated ID back from MongoDB itself:

```
coll.insertOne(document, convertCallback(resultHandler, wr -> useObjectId ? document.getJsonObject(ID_FIELD).getString(JsonObjectCodec.OID_FIELD) : document.getString(ID_FIELD)));
```

**Comment by kennedyoliveira** [comment]
@karianna, thx for your feedback, but i guess you didn't understand what i was asking, i know what you said, the problem is, if the JsonObject i'm saving HAS a ID_FIELD with NULL, then it send the _id as null to mongo and the id doesn't get generated automatically, because the code just try to get the value, doesn't check if the property exists or not.

My english is bad, i hope you can understand, thank you!

**Comment by karianna** [comment]
I think I understand now... The Mongo Java Driver doesn't specify what the behaviour is, so digging deeper, OK from the Mongo Docs directly:

> If the document does not specify an _id field, then MongoDB will add the _id field and assign a unique ObjectId for the document before inserting. Most drivers create an ObjectId and insert the _id field, but the mongod will create and populate the _id if the driver or application does not.
> 
> If the document contains an _id field, the _id value must be unique within the collection to avoid duplicate key error.

So the _as designed_ behaviour is that you're allowed to have one document inserted with a id value set to null.

Perhaps we could log this as a warning, but if we are being strictly supportive of the spec, we should allow it.

**Comment by kennedyoliveira** [comment]
@karianna thanks for the information, so i guess i'm gonna do it in application side then. Thanks for your time! =)
