### ISSUE TITLE
QueryBuilder missing

### ISSUE THREAD

**Issue by kuffel** [vert-x3/vertx-mongo-client#94]
You can build queries in Json and use them in e.g.:

   JsonObject query = new JsonObject("{\"$and\": [ " +
                " {\"points\": {\"$gt\": 30}}, " +
                " {\"points\": {\"$lt\": 60}} " +
                "]}");
    mongoClient.find("books",` query, res -> { ... })

This works fine. I cant find the QueryBuilder class mentioned here:
https://groups.google.com/forum/#!topic/vertx/VOtTa_cEDnM

It is gone in the official Mongo Client 3.3. Is there any other solution?

**Comment by mguillet** [comment]
Are you talking about these ?
http://mongodb.github.io/mongo-java-driver/3.3/builders/filters/

**Comment by kuffel** [comment]
@mguillet Thanks. This snippet does the trick:

Bson b = Filters.and(Filters.gt("calls", 30),Filters.lt("calls", 60));
BsonDocument bsonDocument = b.toBsonDocument(BsonDocument.class, com.mongodb.MongoClient.getDefaultCodecRegistry() );
JsonObject query = new JsonObject(bsonDocument.toJson());
mongoClient.find("books",` query, res -> { ... })

**Comment by mguillet** [comment]
Yeah it's a bit ugly I guess, but I'm sure some nice helper classes can make it better...

I usually build all my query with JsonObject but I'm going to have a closer look at these filters!

**Comment by StephenOTT** [comment]
@kuffel great trick!  should be part of core docs usage

**Comment by StarWindMoonCloud** [comment]
helpful trick, it'll be great if those filters are first citizen in vertx world as well
